name: Run Python Script

on:
  workflow_dispatch: # Manually trigger the workflow

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies (if any)
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas matplotlib plotly
      
      - name: Run Python script
        run: python update_fcr.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Generate HTML file"
          git push